# Generated by Django 5.0.7 on 2024-07-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
